package:
    name: sasa_lammps
    version: 0.2

source:
    path : ..

requirements:
    build:
        - python<3.12.0a0
        - setuptools

    run:
        - python <3.12.0a0
        - https://conda.ovito.org::ovito <=3.10.3
        - conda-forge::matplotlib <=3.9.1
        - conda-forge::numpy <=1.26.4
        - conda-forge::tqdm <=4.66.4
        - conda-forge::scipy <=1.14.0
        - conda-forge::pandas <=2.2.2
        - conda-forge::vmd-python <=3.1.4
