package:
    name: sasaanalysis
    version: 0.1

source:
    path : ..

requirements:
    build:
        - python

    run:
        - python
        - numpy
        - ovito==3.9.2
        - vmd-python==3.1.4

