package:
    name: sasaanalysis
    version: 0.1

source:
    path : ../src

requirements:
    build:
        - python

    run:
        - python
        - numpy==1.26.0
        - ovito==3.9.2
        - vmd-python==3.1.4

